version: '3'
services:
  smartmetserver:
    image: fmidev/smartmetserver:latest
    container_name: smartmetserver
    labels:
      - "traefik.http.routers.smartmetserver.entrypoints=websecure"
      - "traefik.http.routers.smartmetserver.rule=Host(`data.et.meteo.fi`)"
      - "traefik.http.services.smartmetserver.loadbalancer.server.port=8080"
    volumes:
      - /smartmet/data/gfs/ethiopia/surface/querydata:/smartmet/data/gfs/surface
      - /smartmet/data/gfs/ethiopia/pressure/querydata:/smartmet/data/gfs/pressure
      - model-fmi-ecmwf:/smartmet/data/ecmwf
      - smartmetserver-storage-cnf:/etc/smartmet
    networks:
      - traefik-network
    restart: unless-stopped
  ecmwf-surface:
    image: fmidev/fmidownloader
    container_name: fmidownloader-ecmwf-surface
    command:
      - "--producer=ecmwf"
      - "--dir=surface"
      - "--filename=ecmwf_world_surface"
      - "--parameters=Temperature,DewPoint,Humidity,WindDirection,WindSpeedMS,WindGust,TotalCloudCover,Precipitation1h,WeatherSymbol3,Pressure,CAPE,CIN"
    volumes:
      - model-fmi-ecmwf:/tmp
    restart: unless-stopped
volumes:
  smartmetserver-storage-cnf:
  model-fmi-ecmwf:
    name: model-fmi-ecmwf
    
networks:
    traefik-network:
      external: true
